# Generated by Django 3.1.7 on 2021-04-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.BigIntegerField(verbose_name='ИД робота')),
                ('rorot_name', models.CharField(max_length=50, verbose_name='Название')),
                ('team_id', models.BigIntegerField(verbose_name='ИД команды')),
                ('class_id', models.BigIntegerField(verbose_name='ИД класса')),
                ('first_participation_date', models.DateField(verbose_name='Дата первого участия')),
                ('last_participation_date', models.DateField(verbose_name='Дата последнего участия')),
                ('rorot_condition', models.BooleanField(verbose_name='Состояние')),
            ],
        ),
    ]
