# Generated by Django 3.1.7 on 2021-04-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_reg', '0002_auto_20210404_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='first_participation_date',
            field=models.DateField(null=True, verbose_name='Дата первого участия'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='last_participation_date',
            field=models.DateField(null=True, verbose_name='Дата последнего участия'),
        ),
    ]
